server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://db:3306/gifticon_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    cors:
      allowed-origins: "http://localhost:3000"

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.app.giticon_pr.dto
  configuration:
    map-underscore-to-camel-case: true
